name: Outdoorsy .NET Deployment

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Restore dependencies (install NuGet packages)
        run: dotnet restore

      - name: Build and publish the app
        run: |
          dotnet build --no-restore OutdoorsyCloudyMvc.csproj
          dotnet publish -c Release -o ./publish OutdoorsyCloudyMvc.csproj

      - name: Deploy to Web VM
        uses: actions/upload-artifact@v4
        run: |
          echo "Deploying to Web VM at: 4.223.81.235"
          rsync -avz ./publish/ outdoorsyadmin@4.223.81.235:/var/www/outdoorsyapp/
          ssh outdoorsyadmin@4.223.81.235 "sudo systemctl restart outdoorsyapp"
