name: Outdoorsy .NET Deployment

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Setup .NET
        run: |
          export DOTNET_ROOT=/home/outdoorsyadmin/.dotnet
          export PATH=/home/outdoorsyadmin/.dotnet:$PATH
          dotnet --info

      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: |
          export DOTNET_ROOT=/home/outdoorsyadmin/.dotnet
          export PATH=/home/outdoorsyadmin/.dotnet:$PATH
          dotnet restore

      - name: Build with memory limits
        run: |
          export DOTNET_ROOT=/home/outdoorsyadmin/.dotnet
          export PATH=/home/outdoorsyadmin/.dotnet:$PATH
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --no-restore --configuration Release /p:UseSharedCompilation=false

      - name: Build and publish the app
        run: |
          export DOTNET_ROOT=/home/outdoorsyadmin/.dotnet
          export PATH=/home/outdoorsyadmin/.dotnet:$PATH
          dotnet build --no-restore OutdoorsyCloudyMvc.csproj
          dotnet publish -c Release -o ./publish OutdoorsyCloudyMvc.csproj

      - name: Deploy to DBVM
        run: |
          # Add Bastion to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H 4.223.83.148 >> ~/.ssh/known_hosts
          
          # Copy files to DBVM through Bastion using the existing SSH key
          scp -i ~/.ssh/id_ed25519 -o "ProxyCommand ssh -i ~/.ssh/id_ed25519 -A outdoorsyadmin@4.223.83.148 nc %h %p" -r ./publish/* outdoorsyadmin@10.0.2.4:/etc/OutdoorsyCloudyMvc/app/
          
          # Restart the service on DBVM using the existing SSH key
          ssh -i ~/.ssh/id_ed25519 -A -J outdoorsyadmin@4.223.83.148 outdoorsyadmin@10.0.2.4 'sudo systemctl restart outdoorsycloudy.service'

      - name: Cleanup
        if: always()
        run: |
          sudo systemctl restart walinuxagent || true
          sudo apt-get clean
          sudo rm -rf /tmp/*
          pkill -f dotnet || true